### PR TITLE
fix bug in `findDeclarationByName`

### LINKED ISSUE #121: findDeclarationByName sometimes returns `undefined` when it should return a `Declaration`
`wwt decl stemmer.go getRegions`
results in
`Given line number does not yield a supported declaration`

```go
findDeclarationByName(
        node: TreeSitter.SyntaxNode, name: string
    ): Declaration {
        let decl = this.lang.findDeclaration(node);
        if (decl && decl.name === name) return decl;
        node.namedChildren.forEach(child => {
            decl = this.findDeclarationByName(child, name);
            if (decl) return;
        });

        return decl;
    }
```

### PR DESCRIPTION
**Pull request by antonbaumann**
resolve #121

### CODE REVIEW

File: src/Parser.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import TreeSitter from 'tree-sitter';
+import TreeSitter, {SyntaxNode} from 'tree-sitter';
```
Comment (jonhue) [inline src/Parser.ts]: Do we need this change? 🙂

**Review by jonhue — COMMENTED** [review]
👍

**Review by jonhue — APPROVED** [review]
